env:
  browser: true
  es6: true
  jest: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - jest
rules:
  no-unused-vars: ["error", { "argsIgnorePattern": "^_" }]
